keys: &keys
  - &aus_box age1wxfxdf2cjcuy3hmqvdkgswz5w08k245k6h8qewq35st8gqrued2q5wzd8c
  - &malos age12svyxwc0vgvnahqhk57y0n5q9sag3ylmgmv3src6vgqm94yz04hqc3rzjz
  - &mbp age1auth79lm39mvcvmknp0lfhtwx7ugrmtpwvt750pyfm2pj8844pas6peexx
creation_rules:
  - path_regex: secrets/screenshot_key.txt
    key_groups:
      - age: *keys
  - path_regex: secrets/mailpass.txt
    key_groups:
      - age: *keys
  - path_regex: secrets/attic.toml
    key_groups:
      - age: *keys
  - path_regex: secrets/aus-box/.*
    key_groups:
      - age:
          - *aus_box
