#!/bin/sh

echo "Bootstrapping dotfiles"

[ ! -d ~/.vim/bundle/Vundle.vim ] && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

vim +PluginInstall +qall

echo "Building YCM"

cd ~/.vim/bundle/YouCompleteMe
python install.py --verbose --all


echo "Installing omz plugins"
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
[ ! -d "$ZSH_CUSTOM/plugins/notify" ] && git clone https://github.com/marzocchi/zsh-notify.git "$ZSH_CUSTOM/plugins/notify"
[ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] && git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
[ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ] && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
[ ! -d "$ZSH_CUSTOM/plugins/nix-shell" ] && git clone https://github.com/chisui/zsh-nix-shell.git "$ZSH_CUSTOM/plugins/nix-shell"
