#!/bin/sh

echo "Bootstrapping dotfiles"

[ ! -d ~/.vim/bundle/Vundle.vim ] && git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

vim +PluginInstall +qall

echo "Building YCM"

cd ~/.vim/bundle/YouCompleteMe
python install.py --verbose --all
