#!/bin/sh


TEMP_FILE="$XDG_RUNTIME_DIR/statusbar_next_update"
TEMP_UPDATES="$XDG_RUNTIME_DIR/statusbar_pending_updates"
next_update=$(date -d 'now + 30 minutes' +%s)
[ -f "$TEMP_FILE" ] || touch "$TEMP_FILE"
[ -f "$TEMP_UPDATES" ] || touch "$TEMP_UPDATES"
last_updated=$(cat "$TEMP_FILE")


case "$BUTTON" in
    2)
        notify-send "Refreshing updates..."
        echo "-1" > "$TEMP_FILE"
        last_updated="-1"
        ;;
esac


if [ -z "$last_updated" ] || [ "$last_updated" -lt "$(date +%s)" ]; then
    pending=$( (checkupdates ; paru -Qua) | wc -l)
    echo "$next_update" > "$TEMP_FILE"
    echo "$pending" > "$TEMP_UPDATES"
    if [ "$last_updated" == -1 ]; then
        notify-send "Done!"
    fi
else
    pending=$(cat "$TEMP_UPDATES")
fi

if [ "$pending" -gt 0 ]; then
    echo "󰏕 $pending"
fi
