#!/bin/bash

[ $# -ne 1 ] && echo "Usage: $0 <file>" && exit 1

file_name="${1%.*}"
tmp_file=$(mktemp XXXXXX.m4a)
tmp_file2=$(mktemp XXXXXX.m4a)

echo "Copying to m4a"
ffmpeg -y -i "$1" -ss 0 -t 30 -acodec aac -vn -b:a 256k "$tmp_file" &> /dev/null

duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$tmp_file")
crossfade_start=$(echo "$duration - 0.25" | bc -l)

echo "Removing pop"
ffmpeg -y -i "$tmp_file" -af "afade=t=out:st=$crossfade_start:d=0.25" "$tmp_file2" &> /dev/null
mv "$tmp_file2" "${file_name}.m4r"

rm "$tmp_file" "$tmp_file2"
echo "Done!"

