#!/bin/sh
#
if [[ $EUID -ne 0 ]]; then sudo "$0" "$@" || exit 1 ; exit 0; fi

[ "$#" -ne 1 ] && echo "Usage: $0 <mod>" && exit 1


echo "Unloading $1"
rmmod "$1"
sleep 0.5
echo "Loading $1"
modprobe "$1"


