#!/bin/bash

SHUTDOWN="Shutdown"
RESTART="Restart"
SUSPEND="Suspend"

OPTION=$(echo -e "$SUSPEND\n$SHUTDOWN\n$RESTART" | dmenu -c -l 20)

case "$OPTION" in
"$SHUTDOWN")
    echo "Shutting down"
    dmenu_confirm "Shut Down?" && systemctl poweroff
    ;;
"$RESTART")
    echo "Restarting"
    dmenu_confirm "Restart?" && systemctl reboot
    ;;
"$SUSPEND")
    echo "Suspending"
    systemctl suspend
    ;;
esac
