name: Update Nix Cache
on:
  push:
    branches:
      - main
jobs:
  discover-configurations:
    runs-on: ubuntu-latest
    outputs:
      home: ${{ steps.discover-configurations.outputs.home }}
      darwin: ${{ steps.discover-configurations.outputs.darwin }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - id: discover-configurations
        run: |
          echo "Discovering home configurations..."
          configurations=$(nix eval --json .#homeConfigurations --apply builtins.attrNames)
          echo "Discovered the following home configurations: $configurations"
          echo "home={\"configuration\":$configurations}" >> "$GITHUB_OUTPUT"
          echo "Discovering darwin configurations..."
          configurations=$(nix eval --json .#darwinConfigurations --apply builtins.attrNames)
          echo "Discovered the following darwin configurations: $configurations"
          echo "darwin={\"configuration\":$configurations}" >> "$GITHUB_OUTPUT"

  build:
    needs: discover-configurations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{fromJson(needs.discover-configurations.outputs.home)}}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            fallback = true
            substituters = https://cache.mrkirby153.com/mrkirby153-public?priority=43 https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= mrkirby153-public:DxpgFWGtjTaSh6U/bt+Xr5qfj4gVbRjUzaePmA/ndwM= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=
      - name: Set Up Attic
        run: |
          sudo mkdir -p /etc/nix
          echo "machine cache.mrkirby153.com password ${{ secrets.ATTIC_TOKEN }}" | sudo tee /etc/nix/netrc > /dev/null
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com
          curl https://cache.mrkirby153.com/_api/v1/cache-config/mrkirby153-public | jq
          nix run github:zhaofengli/attic#default login mrkirby153-public https://cache.mrkirby153.com ${{ secrets.ATTIC_TOKEN }}
      - name: Build and push system
        run: |
          nix run --extra-experimental-features "nix-command flakes" . "build" -- --flake ".#${{ matrix.configuration }}" --extra-experimental-features "nix-command flakes" -L
          nix run github:zhaofengli/attic#default push mrkirby153-public result -j 2
  build-osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{fromJson(needs.discover-configurations.outputs.darwin)}}
    needs: [discover-configurations, build]
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo mkdir -p /etc/nix
          echo "machine cache.mrkirby153.com password ${{ secrets.ATTIC_TOKEN }}" | sudo tee /etc/nix/netrc > /dev/null
          git config --global url."https://${{secrets.GITHUB_TOKEN}}@github.com".insteadOf https://github.com
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            fallback = true
            substituters = https://cache.mrkirby153.com/mrkirby153-public?priority=43 https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= mrkirby153-public:DxpgFWGtjTaSh6U/bt+Xr5qfj4gVbRjUzaePmA/ndwM= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build and push system
        run: |
          nix run --extra-experimental-features "nix-command flakes" nix-darwin -- build --flake ".#${{ matrix.configuration }}"
          nix run github:zhaofengli/attic#default login mrkirby153-public https://cache.mrkirby153.com ${{ secrets.ATTIC_TOKEN }}
          nix run github:zhaofengli/attic#default push mrkirby153-public result -j 2
